# Generated by Django 4.1.5 on 2023-01-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('product_image', models.ImageField(max_length=255, null=True, upload_to='myphoto/%Y/%m/%d/')),
                ('price', models.PositiveIntegerField()),
                ('product_availability', models.PositiveIntegerField()),
                ('seller', models.CharField(max_length=500)),
                ('product_warranty', models.PositiveIntegerField()),
                ('rating', models.CharField(choices=[('G', 'Good'), ('B', 'Bad'), ('A', 'Average'), ('E', 'Excellent')], max_length=1)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
